package model.pojo;
// Generated Sep 5, 2016 6:56:12 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="order"
    ,schema="public"
)
public class Order  implements java.io.Serializable {


     private int orderId;
     private Customer customer;
     private String amount;
     private String detail;

    public Order() {
    }
    public Order(int orderId, Customer customer) {
        this.orderId = orderId;
        this.customer = customer;
    }
    public Order(int orderId, Customer customer, String amount, String detail) {
       this.orderId = orderId;
       this.customer = customer;
       this.amount = amount;
       this.detail = detail;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="order_id", unique=true, nullable=false)
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    
    @Column(name="amount", length=80)
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }

    
    @Column(name="detail", length=80)
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }

}


